package eu.kanade.tachiyomi.source.online

import android.app.Application
import android.content.Context
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import eu.kanade.tachiyomi.network.AndroidCookieJar
import eu.kanade.tachiyomi.network.GET
import eu.kanade.tachiyomi.network.NetworkHelper
import eu.kanade.tachiyomi.network.asObservableSuccess
import eu.kanade.tachiyomi.network.awaitSuccess
import eu.kanade.tachiyomi.network.newCachelessCallWithProgress
import eu.kanade.tachiyomi.source.CatalogueSource
import eu.kanade.tachiyomi.source.model.FilterList
import eu.kanade.tachiyomi.source.model.MangasPage
import eu.kanade.tachiyomi.source.model.Page
import eu.kanade.tachiyomi.source.model.SChapter
import eu.kanade.tachiyomi.source.model.SManga
import com.shinku.reader.exh.log.maybeInjectEHLogger
import com.shinku.reader.exh.pref.DelegateSourcePreferences
import com.shinku.reader.exh.source.DelegatedHttpSource
import okhttp3.Headers
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.Response
import rx.Observable
import com.shinku.reader.core.common.util.lang.awaitSingle
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import uy.kohesive.injekt.Injekt
import uy.kohesive.injekt.api.get
import java.net.URI
import java.net.URISyntaxException
import java.security.MessageDigest

/**
 * A simple implementation for sources from a website.
 */
@Suppress("unused")
abstract class HttpSource : CatalogueSource {

    /**
     * Network service.
     */
    // SY -->
    protected val network: NetworkHelper by lazy {
        val network = Injekt.get<NetworkHelper>()
        object : NetworkHelper(Injekt.get<Application>(), Injekt.get(), network.isDebugBuild) {
            override val client: OkHttpClient
                get() = delegate?.networkHttpClient ?: network.client
                    .newBuilder()
                    .maybeInjectEHLogger()
                    .build()

            @Deprecated("The regular client handles Cloudflare by default")
            override val cloudflareClient: OkHttpClient
                get() = delegate?.networkHttpClient ?: client

            override val cookieJar: AndroidCookieJar
                get() = network.cookieJar
        }
    }
    // SY <--

    /**
     * Base url of the website without the trailing slash, like: http://mysite.com
     */
    abstract val baseUrl: String

    /**
     * Version id used to generate the source id. If the site completely changes and urls are
     * incompatible, you may increase this value and it'll be considered as a new source.
     */
    open val versionId = 1

    /**
     * ID of the source. By default it uses a generated id using the first 16 characters (64 bits)
     * of the MD5 of the string `"${name.lowercase()}/$lang/$versionId"`.
     *
     * The ID is generated by the [generateId] function, which can be reused if needed
     * to generate outdated IDs for cases where the source name or language needs to
     * be changed but migrations can be avoided.
     *
     * Note: the generated ID sets the sign bit to `0`.
     */
    override val id by lazy { generateId(name, lang, versionId) }

    /**
     * Headers used for requests.
     */
    /* SY --> */
    open /* SY <-- */ val headers: Headers by lazy { headersBuilder().build() }

    /**
     * Default network client for doing requests.
     */
    open val client: OkHttpClient
        // SY -->
        get() = delegate?.baseHttpClient ?: network.client
    // SY <--

    private val hasGetMangaUpdate by lazy {
        try {
            val sourceClass = Class.forName("eu.kanade.tachiyomi.source.Source")
            val httpSourceClass = Class.forName("eu.kanade.tachiyomi.source.online.HttpSource")
            this.javaClass.methods.any { method ->
                method.name == "getMangaUpdate" && 
                method.parameterTypes.size == 5 && 
                method.declaringClass != httpSourceClass && 
                method.declaringClass != sourceClass
            }
        } catch (e: Throwable) {
            false
        }
    }

    /**
     * Generates a unique ID for the source based on the provided [name], [lang] and
     * [versionId]. It will use the first 16 characters (64 bits) of the MD5 of the string
     * `"${name.lowercase()}/$lang/$versionId"`.
     *
     * Note: the generated ID sets the sign bit to `0`.
     *
     * Can be used to generate outdated IDs, such as when the source name or language
     * needs to be changed but migrations can be avoided.
     *
     * @since extensions-lib 1.5
     * @param name [String] the name of the source
     * @param lang [String] the language of the source
     * @param versionId [Int] the version ID of the source
     * @return a unique ID for the source
     */
    @Suppress("MemberVisibilityCanBePrivate")
    protected fun generateId(name: String, lang: String, versionId: Int): Long {
        val key = "${name.lowercase()}/$lang/$versionId"
        val bytes = MessageDigest.getInstance("MD5").digest(key.toByteArray())
        return (0..7).map { bytes[it].toLong() and 0xff shl 8 * (7 - it) }.reduce(Long::or) and Long.MAX_VALUE
    }

    /**
     * Headers builder for requests. Implementations can override this method for custom headers.
     */
    protected open fun headersBuilder() = Headers.Builder().apply {
        add("User-Agent", network.defaultUserAgentProvider())
    }

    /**
     * Visible name of the source.
     */
    override fun toString() = "$name (${lang.uppercase()})"

    /**
     * Get a page with a list of manga.
     * Normally it's not needed to override this method.
     *
     * @param page the page number to retrieve.
     */
    override suspend fun getPopularManga(page: Int): MangasPage {
        val result = fetchPopularManga(page).awaitSingle()
        result.mangas.forEach { manga ->
            manga.memo?.let { MangaMemoCache.put(id, manga.url, it) }
        }
        return result
    }

    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getPopularManga"))
    override fun fetchPopularManga(page: Int): Observable<MangasPage> {
        return client.newCall(popularMangaRequest(page))
            .asObservableSuccess()
            .map { response ->
                popularMangaParse(response)
            }
    }

    /**
     * Returns the request for the popular manga given the page.
     *
     * @param page the page number to retrieve.
     */
    protected abstract fun popularMangaRequest(page: Int): Request

    /**
     * Parses the response from the site and returns a [MangasPage] object.
     *
     * @param response the response from the site.
     */
    protected abstract fun popularMangaParse(response: Response): MangasPage

    /**
     * Get a page with a list of manga.
     * Normally it's not needed to override this method.
     *
     * @param page the page number to retrieve.
     * @param query the search query.
     * @param filters the list of filters to apply.
     */
    override suspend fun getSearchManga(
        page: Int,
        query: String,
        filters: FilterList,
    ): MangasPage {
        val result = fetchSearchManga(page, query, filters).awaitSingle()
        result.mangas.forEach { manga ->
            manga.memo?.let { MangaMemoCache.put(id, manga.url, it) }
        }
        return result
    }

    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getSearchManga"))
    override fun fetchSearchManga(
        page: Int,
        query: String,
        filters: FilterList,
    ): Observable<MangasPage> {
        return Observable.defer {
            try {
                client.newCall(searchMangaRequest(page, query, filters)).asObservableSuccess()
            } catch (e: NoClassDefFoundError) {
                // RxJava doesn't handle Errors, which tends to happen during global searches
                // if an old extension using non-existent classes is still around
                throw RuntimeException(e)
            }
        }
            .map { response ->
                searchMangaParse(response)
            }
    }

    /**
     * Returns the request for the search manga given the page.
     *
     * @param page the page number to retrieve.
     * @param query the search query.
     * @param filters the list of filters to apply.
     */
    protected abstract fun searchMangaRequest(
        page: Int,
        query: String,
        filters: FilterList,
    ): Request

    /**
     * Parses the response from the site and returns a [MangasPage] object.
     *
     * @param response the response from the site.
     */
    protected abstract fun searchMangaParse(response: Response): MangasPage

    /**
     * Get a page with a list of latest manga updates.
     * Normally it's not needed to override this method.
     *
     * @param page the page number to retrieve.
     */
    override suspend fun getLatestUpdates(page: Int): MangasPage {
        val result = fetchLatestUpdates(page).awaitSingle()
        result.mangas.forEach { manga ->
            manga.memo?.let { MangaMemoCache.put(id, manga.url, it) }
        }
        return result
    }

    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getLatestUpdates"))
    override fun fetchLatestUpdates(page: Int): Observable<MangasPage> {
        return client.newCall(latestUpdatesRequest(page))
            .asObservableSuccess()
            .map { response ->
                latestUpdatesParse(response)
            }
    }

    /**
     * Returns the request for latest manga given the page.
     *
     * @param page the page number to retrieve.
     */
    /* SY --> protected <-- SY */
    abstract fun latestUpdatesRequest(page: Int): Request

    /**
     * Parses the response from the site and returns a [MangasPage] object.
     *
     * @param response the response from the site.
     */
    /* SY --> protected <-- SY */
    abstract fun latestUpdatesParse(response: Response): MangasPage

    /**
     * Get the updated details for a manga.
     * Normally it's not needed to override this method.
     *
     * @param manga the manga to update.
     * @return the updated manga.
     */
    @Suppress("DEPRECATION")
    override suspend fun getMangaDetails(manga: SManga): SManga {
        manga.memo?.let { MangaMemoCache.put(id, manga.url, it) }
        return if (hasGetMangaUpdate) {
            MangaUpdateLock.get(id, manga.url).withLock {
                val result = getMangaUpdate(manga, emptyList(), fetchDetails = true, fetchChapters = false).manga
                result.memo?.let { memo ->
                    MangaMemoCache.put(id, manga.url, memo)
                    MangaMemoCache.put(id, result.url, memo)
                }
                result
            }
        } else {
            val result = fetchMangaDetails(manga).awaitSingle()
            result.memo?.let { memo ->
                MangaMemoCache.put(id, manga.url, memo)
                MangaMemoCache.put(id, result.url, memo)
            }
            result
        }
    }

    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getMangaDetails"))
    override fun fetchMangaDetails(manga: SManga): Observable<SManga> {
        return client.newCall(mangaDetailsRequest(manga))
            .asObservableSuccess()
            .map { response ->
                mangaDetailsParse(response).apply { initialized = true }
            }
    }

    /**
     * Returns the request for the details of a manga. Override only if it's needed to change the
     * url, send different headers or request method like POST.
     *
     * @param manga the manga to be updated.
     */
    open fun mangaDetailsRequest(manga: SManga): Request {
        return GET(baseUrl + manga.url, headers)
    }

    /**
     * Parses the response from the site and returns the details of a manga.
     *
     * @param response the response from the site.
     */
    protected abstract fun mangaDetailsParse(response: Response): SManga

    /**
     * Get all the available chapters for a manga.
     * Normally it's not needed to override this method.
     *
     * @param manga the manga to update.
     * @return the chapters for the manga.
     */
    @Suppress("DEPRECATION")
    override suspend fun getChapterList(manga: SManga): List<SChapter> {
        manga.memo?.let { memo ->
            val mUrl = try { manga.url } catch (_: Throwable) { "" }
            if (mUrl.isNotBlank()) {
                MangaMemoCache.put(id, mUrl, memo)
            }
        }
        val safeMangaUrl = try { manga.url } catch (_: Throwable) { "" }
        return if (hasGetMangaUpdate) {
            MangaUpdateLock.get(id, safeMangaUrl).withLock {
                val update = getMangaUpdate(manga, emptyList(), fetchDetails = false, fetchChapters = true)
                update.manga.memo?.let { memo ->
                    val uUrl = try { update.manga.url } catch (_: Throwable) { "" }
                    if (safeMangaUrl.isNotBlank()) MangaMemoCache.put(id, safeMangaUrl, memo)
                    if (uUrl.isNotBlank()) MangaMemoCache.put(id, uUrl, memo)
                }
                val result = update.chapters
                result.forEach { chapter ->
                    chapter.memo?.let { memo ->
                        val cUrl = try { chapter.url } catch (_: Throwable) { "" }
                        if (cUrl.isNotBlank()) {
                            ChapterMemoCache.put(id, cUrl, memo)
                        }
                    }
                }
                result
            }
        } else {
            val result = fetchChapterList(manga).awaitSingle()
            result.forEach { chapter ->
                chapter.memo?.let { memo ->
                    val cUrl = try { chapter.url } catch (_: Throwable) { "" }
                    if (cUrl.isNotBlank()) {
                        ChapterMemoCache.put(id, cUrl, memo)
                    }
                }
            }
            result
        }
    }

    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getChapterList"))
    override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> {
        return client.newCall(chapterListRequest(manga))
            .asObservableSuccess()
            .map { response ->
                chapterListParse(response)
            }
    }

    /**
     * Returns the request for updating the chapter list. Override only if it's needed to override
     * the url, send different headers or request method like POST.
     *
     * @param manga the manga to look for chapters.
     */
    protected open fun chapterListRequest(manga: SManga): Request {
        return GET(baseUrl + manga.url, headers)
    }

    /**
     * Parses the response from the site and returns a list of chapters.
     *
     * @param response the response from the site.
     */
    protected abstract fun chapterListParse(response: Response): List<SChapter>

    /**
     * Parses the response from the site and returns a SChapter Object.
     *
     * @param response the response from the site.
     */
    protected abstract fun chapterPageParse(response: Response): SChapter

    /**
     * Get the list of pages a chapter has. Pages should be returned
     * in the expected order; the index is ignored.
     *
     * @param chapter the chapter.
     * @return the pages for the chapter.
     */
    @Suppress("DEPRECATION")
    override suspend fun getPageList(chapter: SChapter): List<Page> {
        return fetchPageList(chapter).awaitSingle()
    }

    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getPageList"))
    override fun fetchPageList(chapter: SChapter): Observable<List<Page>> {
        return client.newCall(pageListRequest(chapter))
            .asObservableSuccess()
            .map { response ->
                pageListParse(response)
            }
    }

    /**
     * Returns the request for getting the page list. Override only if it's needed to override the
     * url, send different headers or request method like POST.
     *
     * @param chapter the chapter whose page list has to be fetched.
     */
    protected open fun pageListRequest(chapter: SChapter): Request {
        return GET(baseUrl + chapter.url, headers)
    }

    /**
     * Parses the response from the site and returns a list of pages.
     *
     * @param response the response from the site.
     */
    protected abstract fun pageListParse(response: Response): List<Page>

    /**
     * Returns an observable with the page containing the source url of the image. If there's any
     * error, it will return null instead of throwing an exception.
     *
     * @since extensions-lib 1.5
     * @param page the page whose source image has to be fetched.
     */
    open suspend fun getImageUrl(page: Page): String {
        return page.imageUrl ?: fetchImageUrl(page).awaitSingle()
    }

    @Deprecated("Use the non-RxJava API instead", replaceWith = ReplaceWith("getImageUrl"))
    open fun fetchImageUrl(page: Page): Observable<String> {
        return page.imageUrl?.let { Observable.just(it) }
            ?: client.newCall(imageUrlRequest(page))
                .asObservableSuccess()
                .map { imageUrlParse(it) }
    }

    /**
     * Returns the request for getting the url to the source image. Override only if it's needed to
     * override the url, send different headers or request method like POST.
     *
     * @param page the chapter whose page list has to be fetched
     */
    protected open fun imageUrlRequest(page: Page): Request {
        val url = when {
            page.url.startsWith("//") -> "https:${page.url}"
            page.url.startsWith("/") -> baseUrl.trimEnd('/') + page.url
            else -> page.url
        }
        return GET(url, headers)
    }

    /**
     * Parses the response from the site and returns the absolute url to the source image.
     *
     * @param response the response from the site.
     */
    protected abstract fun imageUrlParse(response: Response): String

    /**
     * Returns the response of the source image.
     * Typically does not need to be overridden.
     *
     * @since extensions-lib 1.5
     * @param page the page whose source image has to be downloaded.
     */
    open suspend fun getImage(page: Page, existingSize: Long = 0L): Response {
        return client.newCachelessCallWithProgress(imageRequest(page), page, existingSize)
            .awaitSuccess()
    }

    /**
     * Returns the request for getting the source image. Override only if it's needed to override
     * the url, send different headers or request method like POST.
     *
     * @param page the chapter whose page list has to be fetched
     */
    protected open fun imageRequest(page: Page): Request {
        val imageUrl = page.imageUrl!!
        val url = when {
            imageUrl.startsWith("//") -> "https:$imageUrl"
            imageUrl.startsWith("/") -> baseUrl.trimEnd('/') + imageUrl
            else -> imageUrl
        }
        return GET(url, headers)
    }

    /**
     * Assigns the url of the chapter without the scheme and domain. It saves some redundancy from
     * database and the urls could still work after a domain change.
     *
     * @param url the full url to the chapter.
     */
    fun SChapter.setUrlWithoutDomain(url: String) {
        this.url = getUrlWithoutDomain(url)
    }

    /**
     * Assigns the url of the manga without the scheme and domain. It saves some redundancy from
     * database and the urls could still work after a domain change.
     *
     * @param url the full url to the manga.
     */
    fun SManga.setUrlWithoutDomain(url: String) {
        this.url = getUrlWithoutDomain(url)
    }

    /**
     * Returns the url of the given string without the scheme and domain.
     *
     * @param orig the full url.
     */
    private fun getUrlWithoutDomain(orig: String): String {
        return try {
            val uri = URI(orig.replace(" ", "%20"))
            var out = uri.path
            if (uri.query != null) {
                out += "?" + uri.query
            }
            if (uri.fragment != null) {
                out += "#" + uri.fragment
            }
            out
        } catch (e: URISyntaxException) {
            orig
        }
    }

    /**
     * Returns the url of the provided manga
     *
     * @since extensions-lib 1.4
     * @param manga the manga
     * @return url of the manga
     */
    open fun getMangaUrl(manga: SManga): String {
        return mangaDetailsRequest(manga).url.toString()
    }

    /**
     * Returns the url of the provided chapter
     *
     * @since extensions-lib 1.4
     * @param chapter the chapter
     * @return url of the chapter
     */
    open fun getChapterUrl(chapter: SChapter): String {
        return pageListRequest(chapter).url.toString()
    }

    /**
     * Called before inserting a new chapter into database. Use it if you need to override chapter
     * fields, like the title or the chapter number. Do not change anything to [manga].
     *
     * @param chapter the chapter to be added.
     * @param manga the manga of the chapter.
     */
    open fun prepareNewChapter(chapter: SChapter, manga: SManga) {}

    /**
     * Returns the list of filters for the source.
     */
    override fun getFilterList() = FilterList()

    // EXH -->
    private var delegate: DelegatedHttpSource? = null
        get() = if (Injekt.get<DelegateSourcePreferences>().delegateSources().get()) {
            field
        } else {
            null
        }

    fun bindDelegate(delegate: DelegatedHttpSource) {
        this.delegate = delegate
    }
    // EXH <--
}

object ChapterMemoCache {
    private const val MAX_ENTRIES = 1000

    private val exactCache = object : LinkedHashMap<String, JsonObject>(MAX_ENTRIES, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, JsonObject>?): Boolean {
            return size > MAX_ENTRIES
        }
    }
    private val urlCache = object : LinkedHashMap<String, JsonObject>(MAX_ENTRIES, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, JsonObject>?): Boolean {
            return size > MAX_ENTRIES
        }
    }
    private val purged = java.util.concurrent.atomic.AtomicBoolean(false)

    private fun purgeLegacyPrefs() {
        if (purged.compareAndSet(false, true)) {
            try {
                Injekt.get<Application>().getSharedPreferences("source_chapter_memo_cache", Context.MODE_PRIVATE)
                    .edit().clear().commit()
            } catch (_: Throwable) {}
        }
    }

    private fun normalizeUrl(url: String): String {
        return url.removePrefix("http://")
            .removePrefix("https://")
            .removePrefix("www.")
            .trim()
            .trim('/')
    }

    fun put(sourceId: Long, chapterUrl: String, memo: JsonObject) {
        purgeLegacyPrefs()
        val norm = normalizeUrl(chapterUrl)
        val key = "${sourceId}_$norm"
        synchronized(this) {
            exactCache[key] = memo
            urlCache[norm] = memo
        }
    }

    fun get(sourceId: Long, chapterUrl: String): JsonObject? {
        purgeLegacyPrefs()
        val normTarget = normalizeUrl(chapterUrl)
        synchronized(this) {
            return exactCache["${sourceId}_$normTarget"] ?: urlCache[normTarget]
        }
    }

    fun get(chapterUrl: String): JsonObject? {
        purgeLegacyPrefs()
        val normTarget = normalizeUrl(chapterUrl)
        synchronized(this) {
            return urlCache[normTarget]
        }
    }

    fun ensureChapterMemo(
        sourceId: Long,
        chapter: SChapter,
        mangaUrl: String? = null,
        mangaTitle: String? = null,
        mangaMemo: JsonObject? = null,
    ): JsonObject {
        val existing = chapter.memo?.takeIf { !it.isEmpty() }
            ?: (if (sourceId != 0L) get(sourceId, chapter.url) else null)
            ?: get(chapter.url)

        val existingSlug = (existing?.get("slug") as? JsonPrimitive)?.content
        val existingNumber = (existing?.get("number") as? JsonPrimitive)?.content
        val existingLocked = (existing?.get("isLocked") as? JsonPrimitive)?.content?.toBooleanStrictOrNull()

        val resolvedSlug = if (!existingSlug.isNullOrBlank()) {
            existingSlug
        } else {
            val mSlug = (mangaMemo?.get("slug") as? JsonPrimitive)?.content
            if (!mSlug.isNullOrBlank()) {
                mSlug
            } else if (mangaUrl != null) {
                val cachedManga = if (sourceId != 0L) MangaMemoCache.get(sourceId, mangaUrl) else MangaMemoCache.get(mangaUrl)
                val cSlug = (cachedManga?.get("slug") as? JsonPrimitive)?.content
                if (!cSlug.isNullOrBlank()) {
                    cSlug
                } else {
                    MangaMemoCache.resolveSlug(mangaUrl, mangaTitle)
                }
            } else if (!mangaTitle.isNullOrBlank()) {
                MangaMemoCache.resolveSlug("", mangaTitle)
            } else {
                ""
            }
        }

        val resolvedNumber = if (!existingNumber.isNullOrBlank()) {
            existingNumber
        } else {
            if (chapter.chapter_number >= 0f) {
                if (chapter.chapter_number % 1.0f == 0.0f) {
                    chapter.chapter_number.toInt().toString()
                } else {
                    chapter.chapter_number.toString()
                }
            } else {
                val match = Regex("""(?:chapter\s*|ch\.\s*|#\s*)?(\d+(?:\.\d+)?)""", RegexOption.IGNORE_CASE).find(chapter.name)
                match?.groupValues?.get(1) ?: "1"
            }
        }

        val resolvedLocked = existingLocked ?: false
        val resolvedId = (existing?.get("id") as? JsonPrimitive)?.content ?: chapter.url

        val result = buildJsonObject {
            existing?.forEach { (k, v) -> put(k, v) }
            put("id", JsonPrimitive(resolvedId))
            put("slug", JsonPrimitive(resolvedSlug))
            put("number", JsonPrimitive(resolvedNumber))
            put("isLocked", JsonPrimitive(resolvedLocked))
        }
        chapter.memo = result
        if (sourceId != 0L) {
            put(sourceId, chapter.url, result)
        }
        return result
    }

    fun clear() {
        purgeLegacyPrefs()
        synchronized(this) {
            exactCache.clear()
            urlCache.clear()
        }
    }
}

object MangaMemoCache {
    private val exactCache = java.util.concurrent.ConcurrentHashMap<String, JsonObject>()
    private val urlCache = java.util.concurrent.ConcurrentHashMap<String, JsonObject>()
    private val initialized = java.util.concurrent.atomic.AtomicBoolean(false)

    private val prefs by lazy {
        try {
            Injekt.get<Application>().getSharedPreferences("source_manga_memo_cache", Context.MODE_PRIVATE)
        } catch (_: Throwable) {
            null
        }
    }

    private fun ensureInitialized() {
        if (initialized.compareAndSet(false, true)) {
            try {
                prefs?.all?.forEach { (key, value) ->
                    if (value is String) {
                        try {
                            val obj = Json.parseToJsonElement(value) as? JsonObject
                            if (obj != null) {
                                exactCache[key] = obj
                                val normUrl = key.substringAfter('_')
                                if (normUrl.isNotBlank()) {
                                    urlCache[normUrl] = obj
                                }
                            }
                        } catch (_: Throwable) {}
                    }
                }
            } catch (_: Throwable) {}
        }
    }

    private fun normalizeUrl(url: String): String {
        return url.removePrefix("http://")
            .removePrefix("https://")
            .removePrefix("www.")
            .trim()
            .trim('/')
    }

    fun put(sourceId: Long, mangaUrl: String, memo: JsonObject) {
        ensureInitialized()
        val norm = normalizeUrl(mangaUrl)
        val key = "${sourceId}_$norm"
        if (exactCache[key] == memo) return
        exactCache[key] = memo
        urlCache[norm] = memo
        try {
            prefs?.edit()?.putString(key, memo.toString())?.apply()
        } catch (_: Throwable) {}
    }

    fun get(sourceId: Long, mangaUrl: String): JsonObject? {
        ensureInitialized()
        val normTarget = normalizeUrl(mangaUrl)
        return exactCache["${sourceId}_$normTarget"] ?: urlCache[normTarget]
    }

    fun get(mangaUrl: String): JsonObject? {
        ensureInitialized()
        val normTarget = normalizeUrl(mangaUrl)
        return urlCache[normTarget]
    }

    fun resolveSlug(url: String, title: String?): String {
        val cleanUrl = url.trim().trim('/')
        if (cleanUrl.contains("/")) {
            val segment = cleanUrl.substringAfterLast('/').substringBefore('?')
            if (segment.isNotBlank()) return segment
        }
        if (!title.isNullOrBlank()) {
            val fromTitle = title.lowercase()
                .replace(Regex("[^a-z0-9]+"), "-")
                .trim('-')
            if (fromTitle.isNotBlank()) return fromTitle
        }
        return cleanUrl
    }

    fun ensureMangaMemo(
        sourceId: Long,
        mangaUrl: String,
        title: String? = null,
        existingMemo: JsonObject? = null,
    ): JsonObject {
        val cached = existingMemo ?: get(sourceId, mangaUrl) ?: get(mangaUrl)
        val currentSlug = (cached?.get("slug") as? JsonPrimitive)?.content
        val resolvedSlug = if (!currentSlug.isNullOrBlank()) {
            currentSlug
        } else {
            resolveSlug(mangaUrl, title)
        }
        val currentId = (cached?.get("id") as? JsonPrimitive)?.content ?: mangaUrl

        val result = buildJsonObject {
            cached?.forEach { (k, v) -> put(k, v) }
            put("id", JsonPrimitive(currentId))
            put("slug", JsonPrimitive(resolvedSlug))
        }
        if (cached == null || cached != result) {
            put(sourceId, mangaUrl, result)
        }
        return result
    }

    fun clear() {
        exactCache.clear()
        urlCache.clear()
        try {
            prefs?.edit()?.clear()?.apply()
        } catch (_: Throwable) {}
    }
}

object MangaUpdateLock {
    private val locks = java.util.concurrent.ConcurrentHashMap<String, kotlinx.coroutines.sync.Mutex>()

    fun get(sourceId: Long, mangaUrl: String): kotlinx.coroutines.sync.Mutex {
        val key = "${sourceId}_$mangaUrl"
        return locks.computeIfAbsent(key) { kotlinx.coroutines.sync.Mutex() }
    }
}
